services:
  # observability
  node-exporter:
    image: prom/node-exporter:latest  # Use the latest Node Exporter image

  prometheus:
    image: "prom/prometheus"
    ports:
      - 9090:9090
    volumes:
      - prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"

  grafana:
    image: "grafana/grafana"
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./grafana:/var/lib/grafana

  loki:
    image: "grafana/loki:latest"
    ports:
      - 3100:3100
    volumes:
      - loki-data:/loki

  promtail:
    image: "grafana/promtail:latest"
#    volumes:
#    configure volume for log file here

#    if faced with volume issues, do : 
#
#    sudo chgrp -R nogroup
#    or add user: root
#